### PR TITLE
Add Afrikaans translation

### PR DESCRIPTION
**Pull request by Llewellynvdm**

### CODE REVIEW

**Comment by ai** [comment]
Great! Thanks.

But could you also send PR to R18n: https://github.com/ai/r18n

We need locale file in R18n to use your translation here. I know, that creation locale file is more complicated (especially in Ruby). Ask me any question — I will help.

You need to translate `base/*.yml` and create `locale/*.rb` — don’t worry about `*.rb`, I will fix all.

**Comment by Llewellynvdm** [comment]
Sure I can do that :+1:

**Comment by Llewellynvdm** [comment]
Okay I would need some help with the ordinalize function, would be nice to have :)

```
    def ordinalize(n)
      if (11..13).include?(n % 100)
        "#{n}th"
      else
        case n % 10
        when 1; "#{n}st"
        when 2; "#{n}nd"
        when 3; "#{n}rd"
        else    "#{n}th"
        end
      end
    end
```
Okay let me explain how it works in Afrikaans and you give me the code to add to the file, I already did all the rest.

1st, **2de, 3de, 4de, 5de, 6de, 7de,** _8st,_ **9de, 10de, 11de, 12de, 13de, 14de, 15de, 16de, 17de, 18de, 19de,** 20st, 21st, 22st, 23st, 24st, 25st, 26st, 27st, 28st, 29st, 30st, 31st, 32st, 33st, 34st, 35st, 36st,
37st, 38st, 39st, 40st, 41st... 101st, **102de..** _108st,_ **109de.... 119de,** 120st...

This is what I thought could work.... yet I don't know ruby at all :+1: 
```
   def ordinalize(n)
      if n.between?(2,7)
        "#{n}de"
      elsif n.between?(9,19)
        "#{n}de"
      else
        "#{n}st"
      end
    end
```
Not sure how to add the change for hundreds..

**Comment by ai** [comment]
Interesting case :). Few questions:

1. What about `201…220`?
2. What about `1001…1020`?

**Comment by Llewellynvdm** [comment]
201st, 202de, 203de... 208st, 209de... 219de, 220st
1001st, 1002de, 1003de... 1008st, 1009de... 1019de, 1020st
1101st, 1102de, 1103de... 1108st, 1209de... 1119de, 1120st
1201st, 1202de, 1203de... 1208st, 1209de... 1219de, 1220st

So yes the pattern continues from 2 -> 7 then from 9 -> 19 ```de``` in each hundred and thousand all the rest is just ```st```

**Comment by ai** [comment]
Great, got it. Send PR without this method. I will add code later.

**Comment by ai** [comment]
Thanks, deployed http://easings.net/af

**Pull request merged**
