### PR TITLE
add persian transle

### PR DESCRIPTION
**Pull request by ehsanagh**
hi, i just added persian translate.
and it must be used in rtl direction to have good view.
hope it helps.
Regards

### CODE REVIEW

**Comment by ai** [comment]
Hi. Thanks for translation, I personally very insterest in Iran culture.

But, can you send a PR with farsi locale to [R18n](https://github.com/ai/r18n/tree/master/r18n-core/locales). R18n has not Persian locale, so easing.next will display your translation in incorrect way.

**Comment by ehsanagh** [comment]
sure, i'll make fork from R18n and do it, but can you explain to me exactly what i must to do?
which files i should translate in which folders? i'm not familiar with ruby!

**Comment by ai** [comment]
@ehsanagh you need to add `r18n-core/base/fa.yml` and `r18n-core/locales/fa.rb`.

`r18n-core/base/fa.yml` is a simple config with translations. But `r18n-core/locales/fa.rb` is a little bit complicated, because it is a Ruby file with code. Code is used for pluralization and date formation. but I can help you with Ruby code..

What pluralization has Persian? For example, English has simple one: “1 robot”, “5 robots”. But Russian has more complicated one: “1 робот”, “2 робота”, “5 роботов”.

What is the best way to format date? R18n is very flexible for it. As I understand it will be better to use Persian numerals?

**Comment by ehsanagh** [comment]
don't worry, i can take care of it on my own, i'm nodejs and php developer, but thank you anyway,
yea, you'r right, its better to use Persian numerals,
and about the pluralization it's so simple in Persian for example
1 روبات
2 روبات
5 روبات
like English,

**Comment by ai** [comment]
OK, I will wait for PR to R18n.

**Comment by ehsanagh** [comment]
sure, i'll inform you when i done

**Comment by ehsanagh** [comment]
hi, i made fork from project and i'll start changing ...

**Comment by ehsanagh** [comment]
hi, i translated fa.yml file in r18n , i tried to translate fa.rb but i get confused , 
let me explain why

i iran new year start whit a month named "farvardin" (فروردین) , but the problem is the first day of farvardin is 20 march, so how should i suppose to change this,

month_names: %w{January February March April May June July August
                        September October November December}

farvadin should be the first item instead of January or instead of ( March or April), i have no idea which one is correct,

**Comment by ai** [comment]
Hm. It is interested case :).

But you can totally change date string generation by overriding `Locale#strftime`. For example, it is how I change year for Thai locale: https://github.com/ai/r18n/blob/master/r18n-core/locales/th.rb

**Comment by ai** [comment]
Do you need any help?

**Comment by ai** [comment]
@ehsanagh I can wwrite a Ruby code for date recalculation for a different new year day :).

**Comment by ai** [comment]
@ehsanagh ping :)

**Comment by ai** [comment]
Any help?

**Comment by ai** [comment]
@ehsanagh can I help somehow? Persian locale is really important to me.

**Comment by ai** [comment]
@ehsanagh I add Persian locale and base translation (by Google Translate). Can you check them:
https://github.com/ai/r18n/blob/master/r18n-core/base/fa.yml

**Pull request merged**
