### PR TITLE
make clear that this is for jQuery

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by ai** [comment]
Why jQuery only? This easings can be found in many other JS animations libraries.

**Comment by DanielRuf** [comment]
`.animate()` is only available in frameworks which implement this method but not pure vsnilla JavaScript/ES(5/6).

In this case mention that this is for frameworks and libraries but JavaScript in general is too broad. ;-)

**Comment by DanielRuf** [comment]
I could add / update the heading and note that it is the method signature of jQuery and animation libraries which are compatible and usable as `.animate()` dropin/replacement.

**Comment by ai** [comment]
We can change a title in easing card and keep `JS` label in easings list

**Comment by DanielRuf** [comment]
Do you mean Velocity and others?

**Comment by ai** [comment]
Ouh, I misunderstood commit

**Comment by DanielRuf** [comment]
>We can change a title in easing card and keep JS label in easings list

Sorry but I do not fully understand what you mean.

**Pull request merged**
