### PR TITLE
better heading for jQuery / JavaScript

### PR DESCRIPTION
**Pull request by DanielRuf**
You were a bit too fast ;-)

Oversaw one line and I hope this is better than just jQuery as heading as there are Velocity and probably more that I do not know.

### CODE REVIEW

**Comment by ai** [comment]
Right now link is only to jQuery plugin

**Comment by ai** [comment]
I think in this case `jQuery` is fine

**Comment by DanielRuf** [comment]
Right, but what about the line that I forgot to change?

**Comment by DanielRuf** [comment]
@ai just wanted to ask if the other line should be also changed as I oversaw it in my initial PR ;-)

**Comment by ai** [comment]
Everything looks fine, I already deployed it.

**Comment by DanielRuf** [comment]
Ok.

**Pull request closed without merging**
