### PR TITLE
translate to Vietnamese

### PR DESCRIPTION
**Pull request by nguyenvanduocit**
translate to Vietnamese

### CODE REVIEW

**Comment by ai** [comment]
Awesome! But can you add a Vietnamese locale also to R18n?

easings.net uses R18n for i18n.

**Comment by nguyenvanduocit** [comment]
I'm sorry, but can you show me how ? I just think I only need to translate files in i18n.

**Comment by ai** [comment]
Of course! :) You need to send pull request to `r18n` with `r18n-core/locales/vi.rb` and `r18n-core/base/vi.yml`. You can use other files in dir as example.

If you will feel, that you didn’t understand some fields, keep it in English, I will fix it after PR.

**Comment by nguyenvanduocit** [comment]
in Vietnamese Sunday is "Chủ Nhật" there are two words, how to describe it in ruby ?

**Comment by nguyenvanduocit** [comment]
can you help me to check my pull request on r18n https://github.com/ai/r18n/pull/131

**Pull request merged**
